[package]
name = "pihole-switch"
version = "0.1.0"
edition = "2021"

[dependencies]
pi-hole-api = "0.3.3"
dotenv = "0.15"
tray-item = "0.10.0"
open = "5.3.1"

[build-dependencies]
embed-resource = "2.5"