[package]
name = "pihole-switch"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
tray-item = "0.10.0"
open = "5.3.1"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1", features = ["full"] }
log = "0.4.22"

[build-dependencies]
embed-resource = "2.5"